name: aspectation
version: 0.0.0.0
github: githubuser/aspectation
license-file: [LICENSE-MIT, LICENSE-APACHE]
author: jinnzest
maintainer: jinnzest@users.noreply.github.com
copyright: 2024 jinnzest
extra-source-files:
- README.md
- ChangeLog.md
description: Please see the README on GitHub at <https://github.com/githubuser/aspectation-#readme>
default-extensions: RankNTypes, NoImplicitPrelude, OverloadedStrings , NamedFieldPuns, RecursiveDo, DeriveGeneric, TupleSections, PackageImports, FlexibleInstances, QuasiQuotes, DerivingVia, LambdaCase, StandaloneKindSignatures
dependencies:
- base
library:
    source-dirs:
        - src
    ghc-options:
        - -j
        - -Weverything
        - -Werror
        - -Wno-missing-safe-haskell-mode
        - -Wno-unsafe
        - -Wno-partial-fields
        - -Wno-name-shadowing
        - -Wno-all-missed-specialisations
        - -Wno-missed-specialisations
executables:
    sds:
        main: Main.hs
        source-dirs: app
        ghc-options:
            - -rtsopts
            - -with-rtsopts=-H128m
            - -j
            - -Weverything
            - -Werror
            - -Wno-missing-safe-haskell-mode
            - -Wno-unsafe
            - -Wno-partial-fields
            - -Wno-name-shadowing
            - -Wno-all-missed-specialisations
            - -Wno-missed-specialisations
            - -Wno-unused-packages
        dependencies:
            - aspectation
            - text
tests:
    aspectation-test:
        main: AllTests.hs
        source-dirs: 
        - test
        ghc-options:
            - -rtsopts
            - -with-rtsopts=-H128m
            - -j
            - -Weverything
            - -Werror
            - -Wno-missing-safe-haskell-mode
            - -Wno-unsafe
            - -Wno-partial-fields
            - -Wno-name-shadowing   
            - -Wno-all-missed-specialisations
            - -Wno-missed-specialisations
            - -Wno-unused-packages
        dependencies:
        - tasty

